on:
  push:
    branches:
      - main
      - github-actions
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document (German)
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            ./compile.sh
      - name: Compile LaTeX document (English)
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            ./compile.sh en
      - name: Upload PDF Files to Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.pdf"
          tags: false
          overwrite: true
          draft: true
          update_latest_release: true
